<?php

namespace Database\Seeders;

use App\Models\User;
use App\Core\Enums\Rate;
use App\Core\Enums\JobType;
use App\Models\ResumeSkill;
use Faker\Factory as Faker;
use App\Models\ResumeCompany;
use Illuminate\Database\Seeder;
use App\Core\Enums\LocationType;
use App\Models\ResumeExperience;
use App\Models\ResumeSkillCategory;

class ResumeSeeder extends Seeder
{
    public function run(): void
    {
        $faker = Faker::create('id_ID');

        // ResumeCompany Seeder
        $companies = [
            [
                'name' => 'Gojek',
                'description' => 'An on-demand multi-service platform and digital payment technology group based in Indonesia.',
                'url' => 'https://www.gojek.com',
                'logo' => 'resumes/company/logo/gojek.svg',
            ],
            [
                'name' => 'OVO',
                'description' => 'A digital payment and financial services platform in Indonesia offering e-wallet services.',
                'url' => 'https://www.ovo.id',
                'logo' => 'resumes/company/logo/ovo.svg',
            ],
            [
                'name' => 'Dana',
                'description' => 'A digital wallet service in Indonesia that allows users to make payments and manage finances.',
                'url' => 'https://www.dana.id',
                'logo' => 'resumes/company/logo/dana.svg',
            ],
            [
                'name' => 'LinkAja',
                'description' => 'A digital payment service in Indonesia providing secure transactions and financial management.',
                'url' => 'https://www.linkaja.id',
                'logo' => 'resumes/company/logo/linkaja.svg',
            ],
            [
                'name' => 'Blibli',
                'description' => 'An Indonesian e-commerce platform connecting buyers and sellers for online shopping.',
                'url' => 'https://www.blibli.com',
                'logo' => 'resumes/company/logo/blibli.svg',
            ],
            [
                'name' => 'Zalora',
                'description' => 'An online fashion retailer in Southeast Asia offering a wide range of clothing and accessories.',
                'url' => 'https://www.zalora.com',
                'logo' => 'resumes/company/logo/zalora.svg',
            ],
            [
                'name' => 'Lazada',
                'description' => 'A leading e-commerce platform in Southeast Asia for buying and selling products online.',
                'url' => 'https://www.lazada.com',
                'logo' => 'resumes/company/logo/lazada.svg',
            ],
            [
                'name' => 'JD.id',
                'description' => 'An online shopping platform in Indonesia offering a wide range of products.',
                'url' => 'https://www.jd.id',
                'logo' => 'resumes/company/logo/jd-com.svg',
            ],
            [
                'name' => 'Bhinneka',
                'description' => 'An Indonesian e-commerce site specializing in electronics and IT products.',
                'url' => 'https://www.bhinneka.com',
                'logo' => 'resumes/company/logo/bhinneka.svg',
            ],
            [
                'name' => 'Bukalapak',
                'description' => 'One of Indonesian largest online marketplaces connecting buyers and sellers.',
                'url' => 'https://www.bukalapak.com',
                'logo' => 'resumes/company/logo/bukalapak.svg',
            ],
            [
                'name' => 'Traveloka',
                'description' => 'An online travel agency in Indonesia offering flight and hotel bookings.',
                'url' => 'https://www.traveloka.com',
                'logo' => 'resumes/company/logo/traveloka.svg',
            ],
            [
                'name' => 'Shopee',
                'description' => 'A popular e-commerce platform in Southeast Asia for buying and selling products.',
                'url' => 'https://shopee.com',
                'logo' => 'resumes/company/logo/shopee.svg',
            ],
            [
                'name' => 'Tokopedia',
                'description' => 'An Indonesian technology company operating a marketplace platform for online stores.',
                'url' => 'https://www.tokopedia.com',
                'logo' => 'resumes/company/logo/tokopedia.svg',
            ],
            [
                'name' => 'Google',
                'description' => 'A multinational technology company specializing in Internet-related services and products.',
                'url' => 'https://www.google.com',
                'logo' => 'resumes/company/logo/google.svg',
            ],
            [
                'name' => 'Microsoft',
                'description' => 'A global technology company known for its software products and services.',
                'url' => 'https://www.microsoft.com',
                'logo' => 'resumes/company/logo/microsoft.svg',
            ],
            [
                'name' => 'Apple',
                'description' => 'A leading technology company that designs and manufactures consumer electronics and software.',
                'url' => 'https://www.apple.com',
                'logo' => 'resumes/company/logo/apple.svg',
            ],
            [
                'name' => 'Amazon',
                'description' => 'A multinational technology company focusing on e-commerce and cloud computing.',
                'url' => 'https://www.amazon.com',
                'logo' => 'resumes/company/logo/amazon.svg',
            ],
            [
                'name' => 'Facebook',
                'description' => 'A social media platform that connects people and allows content sharing.',
                'url' => 'https://www.facebook.com',
                'logo' => 'resumes/company/logo/facebook.svg',
            ],
            [
                'name' => 'Instagram',
                'description' => 'A photo and video sharing social networking service owned by Facebook.',
                'url' => 'https://www.instagram.com',
                'logo' => 'resumes/company/logo/instagram.svg',
            ],
            [
                'name' => 'Linkedin',
                'description' => 'A professional networking platform connecting job seekers and employers.',
                'url' => 'https://www.linkedin.com',
                'logo' => 'resumes/company/logo/linkedin.svg',
            ],
            [
                'name' => 'Docker',
                'description' => 'A platform for developing and running applications in containers.',
                'url' => 'https://www.docker.com',
                'logo' => 'resumes/company/logo/docker.svg',
            ],
            [
                'name' => 'AWS',
                'description' => 'Amazon Web Services providing on-demand cloud computing platforms.',
                'url' => 'https://aws.amazon.com',
                'logo' => 'resumes/company/logo/aws.svg',
            ],
            [
                'name' => 'Azure',
                'description' => 'Microsoft Azure, a cloud computing service for building and managing applications.',
                'url' => 'https://azure.microsoft.com',
                'logo' => 'resumes/company/logo/azure.svg',
            ],
            [
                'name' => 'MongoDB',
                'description' => 'A document-oriented NoSQL database known for its flexibility and scalability.',
                'url' => 'https://www.mongodb.com',
                'logo' => 'resumes/company/logo/mongodb.svg',
            ],
            [
                'name' => 'MySQL',
                'description' => 'An open-source relational database management system widely used for web applications.',
                'url' => 'https://www.mysql.com',
                'logo' => 'resumes/company/logo/mysql.svg',
            ],
        ];
        foreach ($companies as $company) {
            ResumeCompany::firstOrCreate(['name' => $company['name']], $company);
        }
        // ResumeExperience Seeder
        for ($i = 0; $i < 50; $i++) {
            ResumeExperience::firstOrCreate([
                'company_id' => ResumeCompany::inRandomOrder()->first()->id,
                'user_id' => 1,
                'job_title' => $faker->jobTitle,
                'description' => (function () use ($faker) {
                    $jobTitle = $faker->jobTitle;
                    return "As a $jobTitle, I was responsible for " . strtolower($faker->paragraph);
                })(),
                'country' => 'Indonesia',
                'province' => $faker->randomElement(['Jawa Barat', 'DKI Jakarta', 'Jawa Tengah', 'Jawa Timur']),
                'regency' => $faker->city,
                'job_type' => $faker->randomElement(JobType::cases()),
                'location_type' => $faker->randomElement(LocationType::cases()),
                'start_date' => $faker->dateTimeBetween('-5 years', '-1 year')->format('Y-m-d'),
                'end_date' => ($endDate = $faker->optional(0.7)->dateTimeBetween('-1 year', 'now')) ? $endDate->format('Y-m-d') : null,
            ]);
        }

        $categories = [
            ['name' => 'Programming'],
            ['name' => 'Design'],
            ['name' => 'Marketing'],
            ['name' => 'Data Analysis'],
            ['name' => 'Project Management'],
            ['name' => 'Writing'],
            ['name' => 'Sales'],
            ['name' => 'Customer Service'],
            ['name' => 'Finance'],
            ['name' => 'Human Resources'],
        ];

        foreach ($categories as $category) {
            ResumeSkillCategory::create($category);
        }

        // ResumeSkill Seeder
        $skillNames = [
            'aarch64',
            'aftereffects',
            'android',
            'androidstudio',
            'angularjs',
            'ansible',
            'apache',
            'appwrite',
            'arduino',
            'argocd',
            'azure',
            'babel',
            'backbonejs',
            'bash',
            'behance',
            'bootstrap',
            'bower',
            'bulma',
            'c',
            'cakephp',
            'centos',
            'ceylon',
            'chrome',
            'circleci',
            'clojurescript',
            'cmake',
            'codecov',
            'codeigniter',
            'codepen',
            'couchdb',
            'cplusplus',
            'csharp',
            'css3',
            'cucumber',
            'd3js',
            'dart',
            'debian',
            'devicon',
            'digitalocean',
            'discordjs',
            'django',
            'docker',
            'doctrine',
            'dot-net',
            'dotnetcore',
            'dropwizard',
            'drupal',
            'eleventy',
            'elixir',
            'elm',
            'embeddedc',
            'erlang',
            'facebook',
            'fastapi',
            'fedora',
            'figma',
            'filezilla',
            'firebase',
            'firefox',
            'flutter',
            'foundation',
            'fsharp',
            'gatling',
            'gatsby',
            'gcc',
            'gentoo',
            'gimp',
            'git',
            'gitlab',
            'gitter',
            'go',
            'godot',
            'google',
            'googlecloud',
            'gradle',
            'grails',
            'graphql',
            'groovy',
            'grunt',
            'gulp',
            'haskell',
            'haxe',
            'heroku',
            'html5',
            'hugo',
            'illustrator',
            'inkscape',
            'intellij',
            'jasmine',
            'java',
            'javascript',
            'jeet',
            'jenkins',
            'jest',
            'jetbrains',
            'jira',
            'jquery',
            'julia',
            'jupyter',
            'karma',
            'kotlin',
            'krakenjs',
            'kubernetes',
            'labview',
            'laravel',
            'linkedin',
            'linux',
            'lua',
            'materialui',
            'matlab',
            'maya',
            'meteor',
            'microsoftsqlserver',
            'minitab',
            'mocha',
            'modx',
            'mongodb',
            'moodle',
            'msdos',
            'mysql',
            'neo4j',
            'nestjs',
            'nixos',
            'nodejs',
            'nodewebkit',
            'nuxtjs',
            'objectivec',
            'ocaml',
            'openal',
            'opencv',
            'opengl',
            'opensuse',
            'opera',
            'perl',
            'phalcon',
            'phoenix',
            'photoshop',
            'php',
            'phpstorm',
            'podman',
            'polygon',
            'postgresql',
            'premierepro',
            'processing',
            'protractor',
            'putty',
            'pycharm',
            'pytest',
            'python',
            'r',
            'rails',
            'rect',
            'redhat',
            'redis',
            'rocksdb',
            'rstudio',
            'ruby',
            'rubymine',
            'rust',
            'safari',
            'salesforce',
            'scala',
            'sdl',
            'sequelize',
            'shotgrid',
            'slack',
            'solidity',
            'spring',
            'spss',
            'sqlalchemy',
            'sqlite',
            'storybook',
            'svelte',
            'swift',
            'tailwindcss',
            'terraform',
            'thealgorithms',
            'tortoisegit',
            'towergit',
            'travis',
            'trello',
            'typescript',
            'typo3',
            'ubuntu',
            'uwsgi',
            'vagrant',
            'vim',
            'visualstudio',
            'vscode',
            'vuejs',
            'vuestorefront',
            'vuetify',
            'weblate',
            'webpack',
            'webstorm',
            'woocommerce',
            'wordpress',
            'xcode',
            'xd',
            'yii'
        ];

        for ($i = 0; $i < 20; $i++) {
            $skillName = $faker->randomElement($skillNames);

            ResumeSkill::firstOrCreate([
                'user_id' => 1,
                'category_id' => ResumeSkillCategory::inRandomOrder()->first()->id,
                'name' => ucfirst($skillName),
                'rate' => $faker->randomElement(Rate::cases()),
                'icon' => 'dev.' . $skillName,
                'icon_color' => [
                    'android' => '#3DDC84',
                    'angularjs' => '#DD0031',
                    'apache' => '#D22128',
                    'apple' => '#000000',
                    'aws' => '#FF9900',
                    'bootstrap' => '#7952B3',
                    'css3' => '#1572B6',
                    'docker' => '#2496ED',
                    'facebook' => '#1877F2',
                    'firebase' => '#FFCA28',
                    'git' => '#F05032',
                    'github' => '#181717',
                    'gitlab' => '#FC6D26',
                    'google' => '#4285F4',
                    'html5' => '#E34F26',
                    'java' => '#007396',
                    'javascript' => '#F7DF1E',
                    'laravel' => '#FF2D20',
                    'linux' => '#FCC624',
                    'mongodb' => '#47A248',
                    'mysql' => '#4479A1',
                    'nodejs' => '#339933',
                    'php' => '#777BB4',
                    'postgresql' => '#336791',
                    'python' => '#3776AB',
                    'react' => '#61DAFB',
                    'redis' => '#DC382D',
                    'ruby' => '#CC342D',
                    'spring' => '#6DB33F',
                    'tailwindcss' => '#06B6D4',
                    'typescript' => '#3178C6',
                    'vuejs' => '#4FC08D',
                ][$skillName] ?? $faker->hexColor,
            ]);
        }
    }
}
