<?php

namespace Database\Factories;

use App\Core\Enums\Rate;
use App\Models\{Category, ResumeSkill};
use Faker\Generator as Faker;
use Illuminate\Database\Eloquent\Factories\Factory;

class ResumeSkillFactory extends Factory
{
    protected $model = ResumeSkill::class;

    public function definition()
    {
        $faker = app(Faker::class);

        $skillName = strtolower($faker->randomElement($this->getSkillNames()));
        $iconPathDev = resource_path("svg/dev/{$skillName}.svg");
        $iconPathCore = resource_path("svg/core/{$skillName}.svg");
        return [
            'user_id' => 1,
            'category_id' => Category::where('scope', 'resume_skill')->inRandomOrder()->first()->id,
            'name' => ucfirst($skillName),
            'rating' => $faker->randomElement(Rate::cases()),
            'icon' => $this->getIcon($iconPathDev, $iconPathCore, $skillName),
        ];
    }
    public function createSampleSkills($count = 20)
    {
        for ($i = 0; $i < $count; $i++) {
            ResumeSkill::firstOrCreate($this->definition());
        }
    }
    protected function getSkillNames()
    {
        return [
            'aarch64',
            'aftereffects',
            'android',
            'androidstudio',
            'angularjs',
            'ansible',
            'apache',
            'appwrite',
            'arduino',
            'argocd',
            'azure',
            'babel',
            'backbonejs',
            'bash',
            'behance',
            'bootstrap',
            'bower',
            'bulma',
            'c',
            'cakephp',
            'centos',
            'ceylon',
            'chrome',
            'circleci',
            'clojurescript',
            'cmake',
            'codecov',
            'codeigniter',
            'codepen',
            'couchdb',
            'cplusplus',
            'csharp',
            'css3',
            'cucumber',
            'd3js',
            'dart',
            'debian',
            'devicon',
            'digitalocean',
            'discordjs',
            'django',
            'docker',
            'doctrine',
            'dot-net',
            'dotnetcore',
            'dropwizard',
            'drupal',
            'eleventy',
            'elixir',
            'elm',
            'embeddedc',
            'erlang',
            'facebook',
            'fastapi',
            'fedora',
            'figma',
            'filezilla',
            'firebase',
            'firefox',
            'flutter',
            'foundation',
            'fsharp',
            'gatling',
            'gatsby',
            'gcc',
            'gentoo',
            'gimp',
            'git',
            'gitlab',
            'gitter',
            'go',
            'godot',
            'google',
            'googlecloud',
            'gradle',
            'grails',
            'graphql',
            'groovy',
            'grunt',
            'gulp',
            'haskell',
            'haxe',
            'heroku',
            'html5',
            'hugo',
            'illustrator',
            'inkscape',
            'intellij',
            'jasmine',
            'java',
            'javascript',
            'jeet',
            'jenkins',
            'jest',
            'jetbrains',
            'jira',
            'jquery',
            'julia',
            'jupyter',
            'karma',
            'kotlin',
            'krakenjs',
            'kubernetes',
            'labview',
            'laravel',
            'linkedin',
            'linux',
            'lua',
            'materialui',
            'matlab',
            'maya',
            'meteor',
            'microsoft Sql Server',
            'minitab',
            'mocha',
            'modx',
            'mongodb',
            'moodle',
            'msdos',
            'mysql',
            'neo4j',
            'nestjs',
            'nixos',
            'nodejs',
            'nodewebkit',
            'nuxtjs',
            'objectivec',
            'ocaml',
            'openal',
            'opencv',
            'opengl',
            'opensuse',
            'opera',
            'perl',
            'phalcon',
            'phoenix',
            'photoshop',
            'php',
            'phpstorm',
            'podman',
            'polygon',
            'postgresql',
            'premierepro',
            'processing',
            'protractor',
            'putty',
            'pycharm',
            'pytest',
            'python',
            'r',
            'rails',
            'rect',
            'redhat',
            'redis',
            'rocksdb',
            'rstudio',
            'ruby',
            'rubymine',
            'rust',
            'safari',
            'salesforce',
            'scala',
            'sdl',
            'sequelize',
            'shotgrid',
            'slack',
            'solidity',
            'spring',
            'spss',
            'sqlalchemy',
            'sqlite',
            'storybook',
            'svelte',
            'swift',
            'tailwindcss',
            'terraform',
            'thealgorithms',
            'tortoisegit',
            'towergit',
            'travis',
            'trello',
            'typescript',
            'typo3',
            'ubuntu',
            'uwsgi',
            'vagrant',
            'vim',
            'visualstudio',
            'vscode',
            'vuejs',
            'vuestorefront',
            'vuetify',
            'weblate',
            'webpack',
            'webstorm',
            'woocommerce',
            'wordpress',
            'xcode',
            'xd',
            'yii'
        ];
    }
    protected function getIcon($iconPathDev, $iconPathCore, $skillName)
    {
        if (file_exists($iconPathDev)) {
            return 'dev.' . $skillName;
        } elseif (file_exists($iconPathCore)) {
            return 'core.' . $skillName;
        } else {
            return 'core.color.git';
        }
    }
}
